---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - CLI_ARGS= #optional
    volumes:
      - /root/backups/config:/config
      - /root/backups:/backups
      - /root/backups/source:/source
    ports:
      - 8200:8200
    restart: unless-stopped
